version: '3.9'

services:
  
  #! Web Server Service
  nginx:
    restart: always
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  #! Database Service
  db:
    # image : mysql
    restart: always
    image: mysql:5.7
    container_name : mysql_hobotta
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: notification
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password

  #! Application Service
  app:
    restart: always
    container_name: app_hobotta
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www   

  #! phpMyAdmin Service
  phpmyadmin:
    restart: always
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_hobotta
    ports:
      - "3400:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password